#!/bin/bash
tuigreet -t \
    --asterisks \
    --user-menu \
    -r \
    --remember-session \
    --g 'Welcome!' \
    --theme 'border=magenta;text=cyan;prompt=green;time=red;action=cyan;button=yellow;container=black;input=red'
